<?php
 /* Saved by FileDatabase */
?><?php
 /* code generated by FileDatabase */
?><?php
$config = new Config();

$config -> set_web_title ('UP Crowd');
$config -> set_web_description ('Spolek studentů a přátel vědy');
$config -> set_web_keywords ('up crowd, upol');
$config -> set_mysql_server ('mysql5.upol.cz');
$config -> set_mysql_database ('upcrowd');
$config -> set_mysql_user ('upcrowd');
$config -> set_mysql_password ('studen759jen');
$config -> set_na_password ('da16981888ff8abcc7d567588f68a7d92bf6550e');
$config -> set_na_password_salt ('w42y31w50u39v65t42v90t68z39s06t48x00w97u53w20v86v41r18z13t50y83x55z34r55t82q66w87x09r88u80');

return $config;

?>