<?php /* Saved by FileDatabase */ ?>
<?php /* code generated by FileDatabase */ ?>
<?php
$config = new Config();

$config -> set_web_title ('UP Crowd');
$config -> set_web_description ('UP Crowd je spolek studentů a přátel vědy na UP');
$config -> set_web_keywords ('studenti,věda,spolek,popularizace,přednášky');
$config -> set_mysql_server ('localhost');
$config -> set_mysql_database ('nanotube_dev');
$config -> set_mysql_user ('nanotube_db_user');
$config -> set_mysql_password ('his_nano_password');
$config -> set_na_password ('fb5cc38d96fe86cfdeabdab6917f519383460aac');
$config -> set_na_password_salt ('r36y43y60r40y11s33w14y90q37z16s76w74y22v93s21y77s47t40t58x90q38s22r26x34r29x85u15t03w19r64');
$config -> set_links_format (null);

return $config;
?>
